name: Firebase Hosting PR Preview

# This workflow is triggered on a pull request to the main branch.
# It automatically builds and previews your Firebase Hosting site.
# This helps you catch issues before merging to production.
on:
  pull_request:
    branches:
      - main

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy PR Preview
        run: |
          firebase hosting:channel:deploy --project $FIREBASE_PROJECT_ID
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}